"""
Protocol types for ONEX SPI interfaces.

This package contains domain-specific protocol types that define the contracts
for data structures used across ONEX service interfaces. All types follow
the zero-dependency principle and use strong typing without Any.
"""

# Core types
from omnibase_spi.protocols.types.core_types import (
    BaseStatus,
    ContextValue,
    HealthStatus,
    LogLevel,
    NodeStatus,
    ProtocolAction,
    ProtocolActionPayload,
    ProtocolConfigValue,
    ProtocolErrorInfo,
    ProtocolLogContext,
    ProtocolLogEntry,
    ProtocolMetadata,
    ProtocolMetadataOperations,
    ProtocolNodeMetadata,
    ProtocolNodeMetadataBlock,
    ProtocolNodeResult,
    ProtocolSchemaObject,
    ProtocolSerializationResult,
    ProtocolState,
    ProtocolSystemEvent,
    ProtocolValidationResult,
)

# Discovery types
from omnibase_spi.protocols.types.discovery_types import (
    CapabilityValue,
    DiscoveryStatus,
    HandlerStatus,
    ProtocolDiscoveryQuery,
    ProtocolDiscoveryResult,
    ProtocolHandlerCapability,
    ProtocolHandlerInfo,
    ProtocolHandlerRegistration,
)

# Event bus types
from omnibase_spi.protocols.types.event_bus_types import (
    AuthStatus,
    EventData,
    EventStatus,
    ProtocolEvent,
    ProtocolEventResult,
    ProtocolEventSubscription,
    ProtocolSecurityContext,
)

# File handling types
from omnibase_spi.protocols.types.file_handling_types import (
    FileContent,
    FileOperation,
    FileStatus,
    ProcessingStatus,
    ProtocolCanHandleResult,
    ProtocolExtractedBlock,
    ProtocolFileContent,
    ProtocolFileFilter,
    ProtocolFileInfo,
    ProtocolFileMetadata,
    ProtocolFileMetadataOperations,
    ProtocolFileTypeResult,
    ProtocolHandlerMatch,
    ProtocolHandlerMetadata,
    ProtocolOnexResult,
    ProtocolProcessingResult,
    ProtocolResultData,
    ProtocolResultOperations,
    ProtocolSerializedBlock,
)

# MCP types
from omnibase_spi.protocols.types.mcp_types import (
    MCPConnectionStatus,
    MCPExecutionStatus,
    MCPLifecycleState,
    MCPParameterType,
    MCPSubsystemType,
    MCPToolType,
    ProtocolMCPDiscoveryInfo,
    ProtocolMCPHealthCheck,
    ProtocolMCPRegistryConfig,
    ProtocolMCPRegistryMetrics,
    ProtocolMCPRegistryStatus,
    ProtocolMCPSubsystemMetadata,
    ProtocolMCPSubsystemRegistration,
    ProtocolMCPToolDefinition,
    ProtocolMCPToolExecution,
    ProtocolMCPToolParameter,
    ProtocolMCPValidationError,
    ProtocolMCPValidationResult,
)

# Workflow orchestration types
from omnibase_spi.protocols.types.workflow_orchestration_types import (
    ExecutionSemantics,
    IsolationLevel,
    ProtocolCompensationAction,
    ProtocolEventProjection,
    ProtocolEventStream,
    ProtocolNodeCapability,
    ProtocolRecoveryPoint,
    ProtocolReplayStrategy,
    ProtocolRetryConfiguration,
    ProtocolServiceDiscovery,
    ProtocolTaskConfiguration,
    ProtocolTaskDependency,
    ProtocolTaskResult,
    ProtocolTimeoutConfiguration,
    ProtocolWorkflowContext,
    ProtocolWorkflowDefinition,
    ProtocolWorkflowEvent,
    ProtocolWorkflowMetadata,
    ProtocolWorkflowSnapshot,
    RetryPolicy,
    TaskPriority,
    TaskState,
    TaskType,
    TimeoutType,
    WorkflowData,
    WorkflowEventType,
    WorkflowState,
)

__all__ = [
    # Core types
    "BaseStatus",
    "ContextValue",
    "HealthStatus",
    "LogLevel",
    "NodeStatus",
    "ProtocolAction",
    "ProtocolActionPayload",
    "ProtocolConfigValue",
    "ProtocolErrorInfo",
    "ProtocolLogContext",
    "ProtocolLogEntry",
    "ProtocolMetadata",
    "ProtocolMetadataOperations",
    "ProtocolNodeMetadata",
    "ProtocolNodeMetadataBlock",
    "ProtocolNodeResult",
    "ProtocolSchemaObject",
    "ProtocolSerializationResult",
    "ProtocolState",
    "ProtocolSystemEvent",
    "ProtocolValidationResult",
    # Workflow orchestration types
    "WorkflowData",
    "WorkflowState",
    "TaskState",
    "TaskType",
    "ExecutionSemantics",
    "RetryPolicy",
    "WorkflowEventType",
    "TimeoutType",
    "TaskPriority",
    "IsolationLevel",
    "ProtocolWorkflowMetadata",
    "ProtocolRetryConfiguration",
    "ProtocolTimeoutConfiguration",
    "ProtocolTaskDependency",
    "ProtocolWorkflowContext",
    "ProtocolTaskConfiguration",
    "ProtocolWorkflowEvent",
    "ProtocolWorkflowSnapshot",
    "ProtocolTaskResult",
    "ProtocolCompensationAction",
    "ProtocolWorkflowDefinition",
    "ProtocolNodeCapability",
    "ProtocolServiceDiscovery",
    "ProtocolRecoveryPoint",
    "ProtocolReplayStrategy",
    "ProtocolEventStream",
    "ProtocolEventProjection",
    # MCP types
    "MCPToolType",
    "MCPParameterType",
    "MCPExecutionStatus",
    "MCPSubsystemType",
    "MCPLifecycleState",
    "MCPConnectionStatus",
    "ProtocolMCPToolParameter",
    "ProtocolMCPToolDefinition",
    "ProtocolMCPSubsystemMetadata",
    "ProtocolMCPSubsystemRegistration",
    "ProtocolMCPToolExecution",
    "ProtocolMCPRegistryMetrics",
    "ProtocolMCPRegistryStatus",
    "ProtocolMCPRegistryConfig",
    "ProtocolMCPHealthCheck",
    "ProtocolMCPDiscoveryInfo",
    "ProtocolMCPValidationError",
    "ProtocolMCPValidationResult",
    # Event bus types
    "AuthStatus",
    "EventData",
    "EventStatus",
    "ProtocolEvent",
    "ProtocolEventResult",
    "ProtocolEventSubscription",
    "ProtocolSecurityContext",
    # Discovery types
    "CapabilityValue",
    "DiscoveryStatus",
    "HandlerStatus",
    "ProtocolDiscoveryQuery",
    "ProtocolDiscoveryResult",
    "ProtocolHandlerCapability",
    "ProtocolHandlerInfo",
    "ProtocolHandlerRegistration",
    # File handling types
    "FileContent",
    "FileOperation",
    "FileStatus",
    "ProcessingStatus",
    "ProtocolCanHandleResult",
    "ProtocolExtractedBlock",
    "ProtocolFileContent",
    "ProtocolFileFilter",
    "ProtocolFileInfo",
    "ProtocolFileMetadata",
    "ProtocolFileMetadataOperations",
    "ProtocolFileTypeResult",
    "ProtocolHandlerMatch",
    "ProtocolHandlerMetadata",
    "ProtocolOnexResult",
    "ProtocolProcessingResult",
    "ProtocolResultData",
    "ProtocolResultOperations",
    "ProtocolSerializedBlock",
]
