# Pre-commit configuration for omnibase_spi
# Copy this to .pre-commit-config.yaml in the root of omnibase_spi

repos:
  - repo: local
    hooks:
      - id: validate-spi-protocols
        name: SPI Protocol Validation
        entry: python scripts/validation/spi_protocol_auditor.py
        language: system
        always_run: true
        stages: [commit]
        description: "Validate SPI protocols for duplicates and quality"

      - id: validate-spi-self-contained
        name: SPI Self-Containment Check
        entry: python -c "
import ast
import sys
from pathlib import Path

violations = []
protocols_path = Path('src/omnibase_spi/protocols')

if protocols_path.exists():
    for py_file in protocols_path.rglob('*.py'):
        try:
            content = py_file.read_text()
            if 'omniagent' in content or 'omnibase_core' in content:
                violations.append(f'{py_file}: Contains non-SPI imports')
        except:
            pass

if violations:
    print('🚨 SPI Self-Containment Violations:')
    for v in violations:
        print(f'   • {v}')
    sys.exit(1)
print('✅ SPI protocols are self-contained')
"
        language: system
        always_run: true
        stages: [commit]
        description: "Ensure SPI protocols don't import external dependencies"

      - id: validate-spi-structure
        name: SPI Directory Structure
        entry: python -c "
import sys
from pathlib import Path

required_dirs = ['core', 'agent', 'workflow', 'file_handling', 'event_bus']
protocols_path = Path('src/omnibase_spi/protocols')

if not protocols_path.exists():
    print('❌ Missing protocols directory structure')
    sys.exit(1)

missing_dirs = []
for req_dir in required_dirs:
    if not (protocols_path / req_dir).exists():
        missing_dirs.append(req_dir)

if missing_dirs:
    print(f'❌ Missing required protocol categories: {missing_dirs}')
    sys.exit(1)

print('✅ SPI directory structure is valid')
"
        language: system
        always_run: true
        stages: [commit]
        description: "Validate SPI protocol directory structure"